load("@rules_go//go:def.bzl", "go_binary")

go_binary(
    name = "ex",
    srcs = ["ex.go"],
    visibility = ["//visibility:public"],
)

go_binary(
    name = "gen",
    srcs = ["gen.go"],
    visibility = ["//visibility:public"],
)
